# Generated by Django 3.0.7 on 2020-07-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_consultapet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nascimento', models.DateField()),
                ('cargo', models.IntegerField(choices=[(1, 'Veterinario'), (2, 'Financeiro'), (3, 'Atendimento')])),
            ],
        ),
    ]
